### ISSUE TITLE
[Bug]: I don't have half of permissions

### ISSUE THREAD

**Issue by goteusz-maszyk** [Kubaryt/GwardiaHub#15]
### Description

So for some reason I lost my owner permissions which is quite bad.

### Steps to reproduce

1. Go to organisation settings
2. Go to people
3. See, that I'm not an admin anymore.

**Comment by Sanielia** [comment]
Well, its just your skill issue for breaking rules

**Comment by Norbiros** [comment]
Behave well, and you'll get admin!

**Comment by goteusz-maszyk** [comment]
1. There were no rules
2. "Behave well" is very broad, it literally doesn't say anything

**Comment by Norbiros** [comment]
Don't merge someone else PRs. Don't commit to main etc. Behave well for 1 week and you'll get owner.
