### ISSUE TITLE
[Feat]: Create GitHub actions

### ISSUE THREAD

**Issue by Norbiros** [Kubaryt/GwardiaHub#2]
### My suggestion

Add new [GitHub action](https://docs.github.com/en/actions/using-workflows/about-workflows) to `.github/workflows` It should contain things like:
 - `ruff` code checks
 - `poetry check`

**Comment by Sanielia** [comment]
Does not [pre-commit](https://github.com/Gwardia-Czapli/GwardiaHub/blob/main/.pre-commit-config.yaml) do it?
