### ISSUE TITLE
[Feat]: Create `Gwardia` app

### ISSUE THREAD

**Issue by Norbiros** [Kubaryt/GwardiaHub#21]
### My suggestion

Create `Gwardia` app ([(tutorial)](https://docs.djangoproject.com/en/5.0/intro/tutorial01/#creating-the-polls-app)). Display simple hello world website.
Move NextMeeting model to `Gwardia/models.py`

**Comment by goteusz-maszyk** [comment]
What do you mean by this?

**Comment by Norbiros** [comment]
![Screenshot_20240327-075249_Fennec.png](https://github.com/Gwardia-Czapli/GwardiaHub/assets/89837724/177dce07-23ab-4236-8003-14fc681602db)

Same as #4
