### ISSUE TITLE
[Enhancement]: Provide Open Graph meta tags

### ISSUE THREAD

**Issue by Norbiros** [Kubaryt/GwardiaHub#29]
### My idea

Add HTML head meta tags like: `og:url`, `og:title`, `og:description` and `theme-color` to make our website better looking in Discord :D

**Comment by WitaLisek** [comment]
We have website on discord? _Provide additional information about what you want this site to look like (less generally)_

**Comment by Norbiros** [comment]
No... When you send some websites as link in for example discord, messenger, twitter they are displayed nicely. 
![Screenshot from 2024-04-06 22-46-12](https://github.com/Gwardia-Czapli/GwardiaHub/assets/89837724/6bc08a70-7ec1-415c-9a53-73832726177f)

Using those open graph tags you can provide site data, so websites like Discords can display it nicely. So provide name, short description, nice color and url.
