### ISSUE TITLE
Rename NextMeeting model to Meeting

### ISSUE THREAD

**Issue by SzczurekYT** [Kubaryt/GwardiaHub#32]
Also remember about migrations!

**Comment by Sanielia** [comment]
uSE iSSUE tEMPlAtES

**Comment by JoaquinFioriti** [comment]
Can i take this issue?

**Comment by Norbiros** [comment]
Sorry, but already @Uneven3106 is assigned. Today I created some new issues, so If you want I can assign you to other one.
