### ISSUE TITLE
Create project icon

### ISSUE THREAD

**Issue by SzczurekYT** [Kubaryt/GwardiaHub#33]
We need a icon for our project, to put it on our site.
We need to decide on how it should look and then someone needs to make it.
- [x] Decide on how the icon should look
- [x] Create the icon
- [ ] Replace the temporary github logo with our icon, and set it to be used as a favicon.

**Comment by SevaTarasyuk** [comment]
@goteusz-maszyk  oddaj mi prawa do assignowania, lub zaassignuj ten issue na mnie

**Comment by toriishia** [comment]
Normal logo:
<img src="https://github.com/Gwardia-Czapli/GwardiaHub/assets/158457522/5676d022-fff9-4e29-b63e-839b8790129f" width="25%">
Long variant:
<img style="background: red" src="https://github.com/Gwardia-Czapli/GwardiaHub/assets/158457522/cbe42807-0295-4d12-9e44-7bccedbc6c93"/>

**Comment by toriishia** [comment]
![long_logo_path](https://github.com/Gwardia-Czapli/GwardiaHub/assets/158457522/94ef6265-0ef4-48e5-8ad2-8a1cc48383e0)
