### ISSUE TITLE
[Bug]: Tailwind sometimes not detected by IDE

### ISSUE THREAD

**Issue by goteusz-maszyk** [Kubaryt/GwardiaHub#66]
### Description

Tailwind is sometimes not detected by Pycharm making it really annoying.

### Steps to reproduce

1. load project
2. try tab-completing tailwind classes
3. _nothing_

### Demonstration(s) and additional context

It can apparently be fixed by installing tailwind via npm dev-dependency

**Comment by Norbiros** [comment]
[Tailwind IntelliSense](https://github.com/tailwindlabs/tailwindcss-intellisense) already supports [tailwind via CDN](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/27). Same feature is planned for Jetbrains' IDEs but it is still not implemented... 

For now, just use `npm install -D tailwindcss` if you have npm & node installed.
