### ISSUE TITLE
[Bug]: Pre commit hooks command in readme

### ISSUE THREAD

**Issue by Norbiros** [Kubaryt/GwardiaHub#9]
### Description

`pre-commit` command doesn't create `.git/hooks/pre-commit`. You need to use `pre-commit install`

### Steps to reproduce

1. Create new repository
2. Go through tutorial in `README.md`
3. Pre commit hook is not created!

### Demonstration(s) and additional context

To fix it, just change command to `pre-commit install`

**Comment by Sanielia** [comment]
I think it should be added to `README.md`
